### PR TITLE
Explicit Cast To `jwt.SignOptions[expiresIn]` To Fix Tsc Compilation Error

### PR DESCRIPTION
**Pull request by taljacob2**
Fixes an error of compiling with `tsc`:

image

Note that this PR has a small conflict with #24, but is easy to resolve.

In case #24 is merged, we should edit the whole `generateTokens` function to:

```js
const generateTokens = (_id: string): { accessToken: string, refreshToken: string } => {
    const random = Math.floor(Math.random() * 1000000);
    const accessToken = jwt.sign(
        {
            _id: _id,
            random: random
        },
        config.token.access_token_secret(),
        { expiresIn: process.env.TOKEN_EXPIRATION as jwt.SignOptions['expiresIn'] });

    const refreshToken = jwt.sign(
        {
            _id: _id,
            random: random
        },
        config.token.access_token_secret(),
        { expiresIn: process.env.REFRESH_TOKEN_EXPIRATION as jwt.SignOptions['expiresIn'] });

    return { accessToken, refreshToken };
}
```

### CODE REVIEW

File: insighthub-backend/src/controllers/auth_controller.ts [hunk 1]
```diff
@@ -31,24 +31,25 @@ const generateTokens = (_id: string): { accessToken: string, refreshToken: strin
...
-        throw new Error("Missing REFRESH_TOKEN_EXPIRATION in environment variables");
-    }
     const refreshToken = jwt.sign(
         {
             _id: _id,
             random: random
         },
         process.env.ACCESS_TOKEN_SECRET,
-        { expiresIn: process.env.REFRESH_TOKEN_EXPIRATION });
+        { expiresIn: process.env.REFRESH_TOKEN_EXPIRATION as jwt.SignOptions['expiresIn'] });
```
Comment (Lina0Elman) [inline insighthub-backend/src/controllers/auth_controller.ts:52]: Great! just rebase or resolve conflicts :)

Comment (taljacob2) [reply insighthub-backend/src/controllers/auth_controller.ts:41]: Fixed in fbc1e96

**Comment by taljacob2** [comment]
Rebased on `main`

**Review by Lina0Elman — APPROVED** [review]
Great!
